sudo: required

language: c

os: linux

compiler: gcc

script:
  - sudo apt update
  - sudo apt install gcc-7 g++-7 cmake libgtest-dev valgrind
  - mkdir build
  - cd build
  - cmake .. && make
  - valgrind --leak-check=full --leak-resolution=med --vgdb=no --track-origins=yes ./Technopark_C_IZ2_tests