addons:
  apt:
    update: true
    packages:
      - valgrind
      - cmake
      - libgtest-dev
      - lcov

sudo: required

language: c

os: linux

compiler: gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - valgrind --leak-check=full --leak-resolution=med --vgdb=no --track-origins=yes ./Technopark_C_IZ2_tests